name: Java PR build (gradle)

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1.4.2
        with:
          java-version: 14
      - name: Check build and test
        run: ./gradlew check javadoc
