name: Java PR build (gradle)

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 14
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 14
      - name: Build with Gradle
        run: ./gradlew build
